# Generated by Django 4.0.10 on 2023-12-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_url_inventory_product_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
    ]
