# Generated by Django 4.0.10 on 2023-12-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_historicalptoduct_type_historicalptoducts_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
