# Generated by Django 4.0.10 on 2023-12-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_db_note_customer_business_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='business_category',
        ),
    ]
