# Generated by Django 4.0.10 on 2023-12-22 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_image_url_inventory_product_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_organization_business_category'),
        ('customers', '0004_remove_customer_email_remove_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.SlugField(blank=True, max_length=8, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('issue_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('ticket_section', models.CharField(blank=True, choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Applications', 'Applications'), ('Infrastructure and Networking', 'Infrastructure and Networking'), ('Database Administrator', 'Database Administrator'), ('Other', 'Other')], max_length=30, null=True)),
                ('urgent_status', models.BooleanField(default=False)),
                ('completed_status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.department')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('order_email', models.CharField(max_length=100)),
                ('order_code', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consumers.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
