# Generated by Django 4.1.12 on 2023-12-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0004_board_board_type_board_board_unique_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistics",
            name="title",
            field=models.CharField(default=-2034, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(default="Board", max_length=30),
        ),
        migrations.AlterField(
            model_name="historicalboard",
            name="title",
            field=models.CharField(default="Board", max_length=30),
        ),
    ]
