# Generated by Django 4.1.12 on 2023-12-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0005_statistics_title_alter_board_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="historicalboard",
            name="id",
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
