# Generated by Django 4.2.7 on 2023-12-03 03:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0006_alter_board_id_alter_historicalboard_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statistics",
            name="api_count",
        ),
        migrations.RemoveField(
            model_name="statistics",
            name="invoice_count",
        ),
        migrations.RemoveField(
            model_name="statistics",
            name="post_count",
        ),
    ]
