# Generated by Django 4.1.12 on 2023-12-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0002_historicalboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="board",
            name="from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="board",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
