# Generated by Django 4.1.12 on 2023-12-02 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "tickets",
            "0007_rename_complained_by_historicalticket_complained_by_and_more",
        ),
        ("users", "0005_historicalprofile_iscustomer_profile_iscustomer"),
        ("boards", "0003_board_days_board_from_date_board_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="board_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="board",
            name="board_unique_id",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="board",
            name="board_url",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="board",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="board",
            name="created_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="board",
            name="period",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="board",
            name="to_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="board_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="board_unique_id",
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="board_url",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="created_for",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="period",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="to_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_count", models.IntegerField(default=0)),
                ("ticket_count", models.IntegerField(default=0)),
                ("user_count", models.IntegerField(default=0)),
                ("message_count", models.IntegerField(default=0)),
                ("api_count", models.IntegerField(default=0)),
                ("task_count", models.IntegerField(default=0)),
                ("note_count", models.IntegerField(default=0)),
                ("invoice_count", models.IntegerField(default=0)),
                ("post_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boards.board",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
