# Generated by Django 4.0.10 on 2023-12-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='db_note',
        ),
        migrations.AddField(
            model_name='customer',
            name='business_category',
            field=models.CharField(choices=[('1', 'Food'), ('2', 'Clothing'), ('3', 'Electronics'), ('4', 'Furniture'), ('5', 'Other')], default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.department'),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
