# Generated by Django 4.2.7 on 2023-12-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_alter_group_created_by_alter_grouppost_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("leader", "Leader"),
                    ("supervisor", "Supervisor"),
                    ("assistant", "Assistant"),
                ],
                max_length=20,
            ),
        ),
    ]
