# Generated by Django 4.0.10 on 2023-12-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='business_category',
            field=models.CharField(choices=[('1', 'Food'), ('2', 'Clothing'), ('3', 'Electronics'), ('4', 'Furniture'), ('5', 'Cosmetics'), ('6', 'Property'), ('7', 'Other')], default='1', max_length=100),
        ),
    ]
