# Generated by Django 4.0.10 on 2023-12-10 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('db_note', models.TextField(default=None, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(default='No bio data', max_length=400)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('common', 'common')], default='common', max_length=6)),
                ('country', models.CharField(choices=[('Saudi Arabia', 'Saudi Arabia'), ('South Sudan', 'South Sudan'), ('Sudan', 'Sudan'), ('Egypt', 'Egypt'), ('common', 'common')], default='common', max_length=200)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('user', 'User')], default='User', max_length=7)),
                ('avatar', models.ImageField(default='avatar.png', upload_to='avatars/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
