# Generated by Django 4.0.10 on 2023-12-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_slug_alter_profile_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_data',
            new_name='user',
        ),
    ]
