# Generated by Django 4.0.10 on 2023-12-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='db_note',
        ),
    ]
