# Generated by Django 4.2.7 on 2023-12-03 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_historicalprofile_id_alter_profile_id"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.profile"
            ),
        ),
        migrations.AlterField(
            model_name="grouppost",
            name="likes",
            field=models.ManyToManyField(default=[], to="users.profile"),
        ),
    ]
